name: Generate Apk

on:
  push:
    branches:
      - "*"

jobs:
  generate-apk:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle with Cache
        uses: gradle/gradle-build-action@v2

      - name: Generate Release Apk
        run: ./gradlew assembleRelease --scan

      - uses: actions/upload-artifact@v3
        with:
          name: Debug Apk
          path: app/build/outputs/apk/release/app-release.apk